"use client";
import localFont from "next/font/local";
import "./globals.css";
import { Box, ThemeProvider } from "@mui/material";
import { lightTheme } from "./Theme";
import { Header } from "./Common/Dependent/Header";
import { createContext, useState } from "react";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});

const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

// export const metadata = {
// 	title: "Bharat Manchanda",
// 	description: "Generated by create next app",
// };
export const AppContext = createContext();

export default function RootLayout({ children }) {
	const [mode, setMode] = useState("light");

	return (
		<html lang="en">
			<body className={`bg-${mode == 'dark' ? 'gray-900' : 'white'} text-${mode == 'dark' ? 'white' : 'black'}`}>
				<>
					<AppContext.Provider value={{mode}}>
						<ThemeProvider theme={lightTheme}>
							<Box mx={{lg:15, xs:2}} my={1}>
								<Header mode={mode} setMode={setMode} />
								{children}
							</Box>
						</ThemeProvider>
					</AppContext.Provider>
				</>
			</body>
		</html>
	);
}
