"use client";
import localFont from "next/font/local";
import "./globals.css";
import { Box, ThemeProvider } from "@mui/material";
import { lightTheme, darkTheme } from "./Theme";
import { Header } from "./Common/Dependent/Header";
import { useState } from "react";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

// export const metadata = {
// 	title: "Bharat Manchanda",
// 	description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
	const [mode, setMode] = useState("light");

	// useEffect(() => {
	// 	const savedTheme = localStorage.getItem('theme');
	// 	if (savedTheme) {
	// 		setMode(savedTheme);
	// 	} else {
	// 		setMode(savedTheme);
	// 	}
	// }, [])

	// useEffect(() => {
	// 	if (mode == "dark") {
	// 		document.documentElement.classList.remove("dark")
	// 		localStorage.setItem('theme', 'dark');
	// 	} else {
	// 		document.documentElement.classList.remove("dark")
	// 		localStorage.setItem('theme', 'light');
	// 	}
	// })

	return (
		<html lang="en">
			{/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> */}
			<body className={`bg-${mode == 'dark' ? 'gray-900' : 'white'} text-${mode == 'dark' ? 'white' : 'black'}`}>
				<ThemeProvider theme={lightTheme}>
					<Box mx={15} my={1}>
						<Header mode={mode} setMode={setMode} />
						{children}
					</Box>
				</ThemeProvider>
			</body>
		</html>
	);
}
